### ISSUE TITLE
URI base path and routes.

### ISSUE THREAD

**Issue by Quantme** [shayanderson/eco#1]
I installed into a folder and added `$eco->conf_uri_base_path = '/panel/';` to `index.php`.

It will be good to have an option for relative paths in config settings. I don't know too much about programming but could be some like:

```php
// set config settings
$eco->conf_uri_base_path = '/panel/';
$eco->conf_uri_relative_path = true;

// set routes
eco([
    '/' => 'IndexController->home',
    '/contact' => 'IndexController->contact',
]);
```

Routes, controllers (and breadcrumbs) will be relative to `conf_uri_base_path` and if we move/copy project could modify just one var/parameter. The only minor problem could be when setting an 'absolute link' on routes/controllers/breadcrumbs like:

```php
// set routes
eco([
    '/' => 'IndexController->home',
    '/youtube' => 'youtube.com/MyChannel',
]);
```

Thank you in advance for your time and attention.

**Comment by shayanderson** [comment]
This is possible using the config setting 'conf_uri_base_path', for example:
$eco->conf_uri_base_path = '/panel/';

The Breadcrumb class is a helper class so is not tied to core logic - so simply using a URL filter would solve that problem.
